# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HologramSeg' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HologramSeg
  pod 'TensorFlowLiteSwift'
#  pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'

end
